CREATE DATABASE EMPDATABASE;
use EMPDATABASE;
-- DROP DATABASE EMPDATABASE;
-- CREATING DEPARTMENT TABLES
CREATE TABLE DEPARTMENT(
DeptID INT PRIMARY KEY,
DeptName VARCHAR(50),
Location VARCHAR(50)
);
-- CREATING TABLE FOR EMPLOYEE DATA
CREATE TABLE EMPLOYEE(
EmpID INT PRIMARY KEY,
EmpName VARCHAR(50),
Gender CHAR(1),
DOB DATE,
DeptID INT,
JoinDate DATE,
Position VARCHAR(50),
foreign key(DeptID)references DEPARTMENT(DeptID)
);
-- DROP TABLE EMPLOYEE;
-- SELECT * FROM EMPLOYEE;
CREATE TABLE ATTENDANCE(
AttID INT PRIMARY KEY,
EmpID INT,
AttDate DATE,
Status VARCHAR(10),
foreign key(EmpID) references EMPLOYEE(EmpID)
);
-- CREATE TABLE FOR EMPLOYEE SALARY
CREATE TABLE SALARY(
SalaryID INT PRIMARY KEY,
EmpID INT,
BaseSalary DECIMAL(10,2),
Bonus DECIMAL(10,2),
Deduction DECIMAL(10,2),
NetSalary DECIMAL(10,2),
foreign key(EmpID) references ATTENDANCE(EmpID)
);
-- CREATE TABLE FOR PROJECT
CREATE TABLE PROJECT(
ProjectID INT PRIMARY KEY,
ProjectName VARCHAR(50),
EmpID INT,
Role VARCHAR(50),
foreign key(EmpID) references EMPLOYEE(EmpID)
);
